version: '3.9'

networks:
  dev_network:

services:
  redis:
    image: redis:latest
    hostname: redis
    expose:
      - 6379
    networks:
      dev_network:
        aliases:
          - db-redis
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/djangoProjectFinalWork
    ports:
      - 8000:8000
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    env_file:
      - .env
    networks:
      dev_network:
    depends_on:
      - db
    links:
      - db:db
    container_name: django_app
    command: sh -c "python manage.py makemigrations  && python manage.py migrate &&  python manage.py runserver_plus"
  db:
    image: postgres:latest
    container_name: ${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      dev_network:
  celery:
    build:
      context: .
    entrypoint: celery -A djangoProjectFinalWork.tasks worker -l INFO
    container_name: celery
    volumes:
      - .:/djangoProjectFinalWork
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DJANGO_DB: postgresql
    networks:
      dev_network:
    links:
      - redis
    depends_on:
      - redis
volumes:
   postgres_data: {}
   djangoProjectFinalWork: {}
