version: '3.9'

networks:
  dev_network:

services:
  redis:
    image: redis:latest
    hostname: redis
    expose:
      - 6379
    networks:
      dev_network:
        aliases:
          - db-redis
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/djangoProjectFinalWork
    ports:
      - 8000:8000
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    env_file:
      - .env
    networks:
      dev_network:
    container_name: django_app
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  postgres:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      dev_network:
  celery:
    build:
      context: .
    entrypoint: celery -A djangoProjectFinalWork.tasks worker -l INFO
    container_name: celery
    volumes:
      - .:/djangoProjectFinalWork
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DJANGO_DB: postgresql
#      POSTGRES_HOST: db
#      POSTGRES_NAME: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_PORT: 5432
    networks:
      dev_network:
    links:
      - redis
    depends_on:
      - redis
#      - django
#    dashboard:
#      build: ./project
#      command: flower -A core --port=5555 --broker=redis://redis:6379/0
#      ports:
#        - 5555:5555
#      environment:
#        - DEBUG=1
#        - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
#        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#        - CELERY_BROKER=redis://redis:6379/0
#        - CELERY_BACKEND=redis://redis:6379/0
#      depends_on:
#        - webz
volumes:
   postgres_data: {}
   djangoProjectFinalWork: {}
